### Create data for thetas:

In [1]:
import numpy as np

In [2]:
nbr_thetas = 5
theta_0 = np.linspace(start=-1, stop=3, num=nbr_thetas)
theta_1 = np.linspace(start=-1, stop=3, num=nbr_thetas)

#### theta_0 and theta_1 are one-dimensional:

In [3]:
print(theta_0.shape)
print(theta_0)
print()
print(theta_1.shape)
print(theta_1)

(5,)
[-1.  0.  1.  2.  3.]

(5,)
[-1.  0.  1.  2.  3.]


#### Convert to two dimensions:

In [4]:
plot_t0, plot_t1 = np.meshgrid(theta_0, theta_1)

In [5]:
print(plot_t0.shape)
print(plot_t0)
print()
print(plot_t1.shape)
print(plot_t1)

(5, 5)
[[-1.  0.  1.  2.  3.]
 [-1.  0.  1.  2.  3.]
 [-1.  0.  1.  2.  3.]
 [-1.  0.  1.  2.  3.]
 [-1.  0.  1.  2.  3.]]

(5, 5)
[[-1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.]
 [ 3.  3.  3.  3.  3.]]


### Nested for loop practice:

In [6]:
for i in range(3):
    if i != 0:
        print()
    for j in range(3):
        print(f'[{i}][{j}]')

[0][0]
[0][1]
[0][2]

[1][0]
[1][1]
[1][2]

[2][0]
[2][1]
[2][2]


#### Create a 2D arrays of just zeros:

In [7]:
plot_cost = np.zeros( (nbr_thetas, nbr_thetas) )
print(plot_cost.shape)
print(plot_cost)

(5, 5)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### Print row values (horizontal):

In [8]:
for i in range(nbr_thetas):
    if i != 0:
        print()
    for j in range(nbr_thetas):
        print(plot_t0[i][j])

-1.0
0.0
1.0
2.0
3.0

-1.0
0.0
1.0
2.0
3.0

-1.0
0.0
1.0
2.0
3.0

-1.0
0.0
1.0
2.0
3.0

-1.0
0.0
1.0
2.0
3.0


#### Print column values (vertical):

In [9]:
for i in range(nbr_thetas):
    if i != 0:
        print()
    for j in range(nbr_thetas):
        print(plot_t0[j][i])

-1.0
-1.0
-1.0
-1.0
-1.0

0.0
0.0
0.0
0.0
0.0

1.0
1.0
1.0
1.0
1.0

2.0
2.0
2.0
2.0
2.0

3.0
3.0
3.0
3.0
3.0


### Calculate MSE using nested for loops: